apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pod-node-matrix
spec:
  version: {{ .TagName }}
  homepage: https://github.com/ardaguclu/kubectl-pod-node-matrix
  shortDescription: Show pod status x node matrix in table view
  description: |
    This plugin shows pod x node matrix with suitable colors to mitigate troubleshooting effort.
  caveats: |
    * Due to terminal width limitation, it does not support huge number of nodes.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/ardaguclu/kubectl-pod-node-matrix/releases/download/{{ .TagName }}/kubectl-pod-node-matrix_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
      bin: kubectl-pod-node-matrix
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/ardaguclu/kubectl-pod-node-matrix/releases/download/{{ .TagName }}/kubectl-pod-node-matrix_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
      bin: kubectl-pod-node-matrix
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/ardaguclu/kubectl-pod-node-matrix/releases/download/{{ .TagName }}/kubectl-pod-node-matrix_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
      bin: kubectl-pod-node-matrix
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/ardaguclu/kubectl-pod-node-matrix/releases/download/{{ .TagName }}/kubectl-pod-node-matrix_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
      bin: kubectl-pod-node-matrix.exe