apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: dapply
spec:
  version: v0.24.3
  homepage: https://github.com/ardaguclu/kubectl-dapply
  shortDescription: Apply resources only after showing diff and user accepts to proceed
  description: |
    Apply a configuration to a resource by file name or stdin only after running the
    diff command for given resource(s) and user accepts to proceed.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/ardaguclu/kubectl-dapply/releases/download/v0.1.0/kubectl-dapply_v0.24.3_darwin_amd64.tar.gz
      sha256: c4b356a26d5cb9cc3edde0b9d7330308a7a40504c0b012a98ac14deb780b8a3e
      bin: kubectl-dapply
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/ardaguclu/kubectl-dapply/releases/download/v0.1.0/kubectl-dapply_v0.24.3_darwin_arm64.tar.gz
      sha256: 03601ae3a897e7c2a281e6c51ac21dbd8124008e8734dd5ed2bb13282a509807
      bin: kubectl-dapply
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/ardaguclu/kubectl-dapply/releases/download/v0.1.0/kubectl-dapply_v0.24.3_linux_amd64.tar.gz
      sha256: a489b7c1da08084839f3d2c37e478c1e6c4fe8df5039a160060bcfd701404585
      bin: kubectl-dapply
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/ardaguclu/kubectl-dapply/releases/download/v0.0.2/kubectl-dapply_v0.24.3_windows_amd64.tar.gz
      sha256: a5b8764f6981215f7b1f358b53fa962459368f7647b6cb52397f86e37ac3870f
      bin: kubectl-dapply.exe